### ISSUE TITLE
[BUG] Mixed types in unit.move field

### ISSUE THREAD

**Issue by brittonhayes** [brittonhayes/warhammer-aos#22]
Move field is string in this army

https://github.com/brittonhayes/warhammer-aos/blob/93d5085e3025b899a7238b3331a5c2056620e16a/data/json/blades_of_khorne.json#L7

But is an array of objects in this army
https://github.com/brittonhayes/warhammer-aos/blob/93d5085e3025b899a7238b3331a5c2056620e16a/data/json/kharadron_overlords.json#L274-L300

We'll want to consolidate this into one type

**Comment by Zferg** [comment]
Moved to my to-do list for tomorrow, sec+ chapter took longer than expected.

**Comment by brittonhayes** [comment]
Relevant discussion for this issue https://github.com/brittonhayes/warhammer-aos/discussions/23
