### ISSUE TITLE
[BUG] Mixed types in field melee_weapons.attacks 

### ISSUE THREAD

**Issue by brittonhayes** [brittonhayes/warhammer-aos#24]
**Describe the issue**
Similar to issue #22, the `melee_weapons.attacks` field has results with both arrays of objects as well as strings. This goes against the JSON schema. 

**Expected behavior**
A consistent data type across the board for this field. Whether that is string or array of objects. 

If we want it to be an array of objects, we'll have to update the schema here:
```
# schema.json
...
"attacks": {
  "$id": "#/properties/units/items/anyOf/0/properties/melee_weapon/items/anyOf/0/properties/attacks",
  "type": "string",
  "title": "The attacks schema",
  "description": "An explanation about the purpose of this instance.",
  "default": ""
},
...
```

**Comment by Zferg** [comment]
Moved to my to-do list for tomorrow, sec+ chapter took longer than expected.

**Comment by brittonhayes** [comment]
Relevant discussion for this issue https://github.com/brittonhayes/warhammer-aos/discussions/23
